[package]
name = "basic_receiving_actor"
version = "0.1.0"
edition = "2021"

[dependencies]
frc46_token = { version = "1.1.0", path = "../../../../frc46_token" }
frc42_dispatch = { path = "../../../../frc42_dispatch" }
fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "0.3.0"
fvm_sdk = { version = "3.0.0-alpha.8" }
fvm_shared = { version = "3.0.0-alpha.8" }

[build-dependencies]
wasm-builder = "3.0"