[package]
name = "basic_nft_actor"
version = "0.1.0"
edition = "2021"

[dependencies]
frc46_token = { path = "../../../../frc46_token" }
frcxx_nft = { path = "../../../../frcxx_nft" }
frc42_dispatch = { path = "../../../../frc42_dispatch" }
fvm_actor_utils = { version = "0.1.0", path = "../../../../fvm_actor_utils" }
fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "0.3.0"
fvm_sdk = { version = "3.0.0-alpha.15" }
fvm_shared = "3.0.0-alpha.13"
serde = { version = "1.0.136", features = ["derive"] }
serde_tuple = { version = "0.5.0" }
thiserror = { version = "1.0.31" }

[build-dependencies]
wasm-builder = "3.0"
