[workspace]

members = [
    "dispatch_examples/greeter",
    "frc42_dispatch",
    "frc42_dispatch/hasher",
    "frc42_dispatch/macros",
    "frc42_dispatch/macros/example",
    "frc46_token",
    "frc46_factory_token",
    "frc46_factory_token/token_impl",
    "frc53_nft",
    "fvm_actor_utils",
    "fvm_dispatch_tools",
    "testing/fil_token_integration",
    "testing/fil_token_integration/actors/basic_nft_actor",
    "testing/fil_token_integration/actors/basic_receiving_actor",
    "testing/fil_token_integration/actors/basic_token_actor",
    "testing/fil_token_integration/actors/basic_transfer_actor",
    "testing/fil_token_integration/actors/frc46_test_actor",
    "testing/fil_token_integration/actors/frc53_test_actor"
]

[workspace.dependencies]
cid = { version = "0.10.1", default-features = false, features = ["serde-codec"] }
fvm_sdk = "~3.3.0"
fvm_shared = "~3.4.0"
fvm_integration_tests = "~3.1.0"
fvm_ipld_encoding = "0.4.0"
fvm_ipld_blockstore = "0.2.0"
fvm_ipld_hamt = "0.7.0"
fvm_ipld_amt = { version = "0.6.0", features = ["go-interop"] }
fvm_ipld_bitfield = "0.5.4"
