[package]
name = "greeter"
version = "0.1.0"
edition = "2021"

[dependencies]
frc42_dispatch = { path = "../../frc42_dispatch" }
fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding = "0.3.0"
fvm_sdk = { version = "3.0.0-alpha.15" }
fvm_shared = { version = "3.0.0-alpha.13" }

[dev-dependencies]
cid = { version = "0.8.5", default-features = false }
fvm = { version = "3.0.0-alpha.5", default-features = false }
fvm_integration_tests = "2.0.0-alpha.1"
actors-v10 = { package = "fil_builtin_actors_bundle", git = "https://github.com/filecoin-project/builtin-actors", branch = "next", features = ["m2-native"] }

[build-dependencies]
wasm-builder = "3.0"
